USE `municipalidad_trancas`;

CREATE TABLE IF NOT EXISTS `tourism_places` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `slug` VARCHAR(90) NOT NULL,
  `name` VARCHAR(180) NOT NULL,
  `category` VARCHAR(80) NOT NULL DEFAULT '',
  `short_description` TEXT NOT NULL,
  `full_description` LONGTEXT NOT NULL,
  `image_url` VARCHAR(2048) NOT NULL DEFAULT '',
  `gallery_json` JSON NOT NULL,
  `address` VARCHAR(260) NOT NULL DEFAULT '',
  `how_to_get` TEXT NOT NULL,
  `map_embed_url` VARCHAR(2048) NOT NULL DEFAULT '',
  `map_external_url` VARCHAR(2048) NOT NULL DEFAULT '',
  `contact_phone` VARCHAR(80) NOT NULL DEFAULT '',
  `contact_email` VARCHAR(180) NOT NULL DEFAULT '',
  `contact_whatsapp` VARCHAR(80) NOT NULL DEFAULT '',
  `visiting_hours` VARCHAR(180) NOT NULL DEFAULT '',
  `sort_order` INT UNSIGNED NOT NULL DEFAULT 0,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `tourism_places_slug_unique` (`slug`),
  UNIQUE KEY `tourism_places_name_unique` (`name`),
  KEY `tourism_places_sort_idx` (`sort_order`),
  KEY `tourism_places_active_idx` (`is_active`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO `tourism_places` (
  `slug`,
  `name`,
  `category`,
  `short_description`,
  `full_description`,
  `image_url`,
  `gallery_json`,
  `address`,
  `how_to_get`,
  `map_embed_url`,
  `map_external_url`,
  `contact_phone`,
  `contact_email`,
  `contact_whatsapp`,
  `visiting_hours`,
  `sort_order`
)
SELECT
  'dique-el-potrero',
  'Dique El Potrero',
  'Naturaleza',
  'Entorno natural ideal para actividades al aire libre.',
  'El Dique El Potrero es uno de los puntos más visitados de Trancas por su paisaje abierto, su tranquilidad y su valor recreativo para vecinos y visitantes.',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1400&q=80',
  JSON_ARRAY(),
  'Trancas, Tucumán',
  'Accedé por rutas locales señalizadas desde el centro de Trancas.',
  '',
  '',
  '',
  '',
  '',
  'Todos los días',
  10
WHERE NOT EXISTS (SELECT 1 FROM `tourism_places`);
